services:
  jekyll:
    image: ruby:3.2
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - ../willchurchill.github.io:/srv/willchurchill.github.io
      - bundle-cache:/usr/local/bundle
    environment:
      BUNDLE_PATH: /usr/local/bundle
    command: >
      bash -lc "bundle install &&
      bundle exec jekyll serve --destination ../willchurchill.github.io/ --host 0.0.0.0 --port 4000 --livereload --force_polling"

volumes:
  bundle-cache:
